
services:
 
  web:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/ticketsystemapi
    ports:
      - "8090:8000"  # Changed host port to 8080
    environment:
      - DATABASE_NAME=dbticketsystem
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=S3cret
      - DATABASE_HOST=10.0.0.50

