version: '3.8'

services:
 
  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/ticketsystemapi
    ports:
      - "8080:8000"  # Changed host port to 8080
    environment:
      - DATABASE_NAME=dbticketsystem
      - DATABASE_USER=userticketsystem
      - DATABASE_PASSWORD=password01
      - DATABASE_HOST=0.0.0.0

